### ISSUE TITLE
Resolve Deprecated Numpy Attribute Error Introduced in Commit 99153902f47a2e7faedc69d3740fd173fbf7891d

### ISSUE THREAD

**Issue by eliseoe** [MagriLab/EchoStateNetwork#10]
**Error Message:** 
AttributeError: module 'numpy' has no attribute 'int'.

**Description:**
The commit with ID 99153902f47a2e7faedc69d3740fd173fbf7891d has introduced issues related to the deprecation of np.int in NumPy, resulting in the mentioned attribute error. I believe this is because there is no compatibility with newer versions of NumPy. We should either agree on the same numpy version or resolve this for future versions. 

**Current Environment**
- NumPy: 1.25.2 (most recent is 1.26.2)
